---
- name: create base system directories
  file:
    path: "/usr/local/{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: "{{ item.state }}"
  with_flattened:
    - "{{ common_directories }}"
    - "{{ specific_directories }}"

- name: create /usr/local links
  file:
    path: "/usr/local/{{ item.dest }}"
    src: "/usr/local/{{ item.src }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: "{{ item.state }}"
  with_flattened:
    - "{{ common_links }}"
    - "{{ specific_links }}"
