---
- name: create base system directories
  file:
    path: "/usr/local/{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: "{{ item.state }}"
  with_flattened:
    - "{{ system_directories['common'] }}"
    - "{{ system_directories[ansible_system] }}"

- name: create /usr/local links
  file:
    path: "/usr/local/{{ item.dest }}"
    src: "/usr/local/{{ item.src }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: "{{ item.state }}"
  with_flattened:
    - "{{ system_links['common'] }}"
    - "{{ system_links[ansible_system] }}"
