---

- block:
    - name: fuse on FreeBSD
      block:
        - name: install fuse packages
          pkgng:
            name: "{{ fuse_packages }}"
            state: latest

        - name: set fuse sysctl
          sysctl:
            name: "{{ item.name }}"
            value: "{{ item.value }}"
            state: present
            reload: yes
            sysctl_file: "{{ sysctl_conf }}"
          loop: "{{ fuse_sysctls }}"

        - name: load fuse kernel module
          include: kernel_module.yml module_name=fuse module_status=enable

      when: ansible_system == 'FreeBSD'

  when: want_fuse
