---
- group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.gid | default(omit) }}"
    system: "{{ item.system | default('no') }}"
  with_items: "{{ common_groups + specific_groups }}"
