---

- name: install logrotate package
  package:
    name: logrotate
    state: present

- name: set logrotate.d directory
  file:
    path: "{{ system_logrotate_d }}"
    owner: root
    group: "{{ root_group }}"
    mode: "0755"
    state: directory

- block:
    - name: check logrotate.conf
      stat:
        path: "{{ system_logrotate_conf }}"
      register: t_system_logrotate_conf

    - name: check logrotate.conf.sample
      stat:
        path: "{{ system_logrotate_conf }}.sample"
      register: t_system_logrotate_conf_sample

    - name: deploy logrotate.conf
      template:
        src: "logrotate/logrotate.conf"
        dest: "{{ system_logrotate_conf }}"
        mode : "0644"
        owner: root
        group: "{{ root_group }}"
      when: not t_system_logrotate_conf.stat.exists or (t_system_logrotate_conf_sample.stat.exists and t_system_logrotate_conf_sample.stat.checksum == t_system_logrotate_conf.stat.checksum)

- name: set logrotate.conf options
  lineinfile:
    path: "{{ system_logrotate_conf }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ system_logrotate_conf_entries }}"

- name: set cron.daily dir
  file:
    path: "{{ system_cron_daily_d }}"
    owner: root
    group: "{{ root_group }}"
    mode: "0755"
    state: directory

- name: deploy cron.daily logrotate task
  template:
    src: "logrotate/cron.daily/logrotate"
    dest: "{{ system_cron_daily_d }}/logrotate"
    mode : "0644"
    owner: root
    group: "{{ root_group }}"
