---

- include: context.yml

- block:
    - include_tasks: hosttype.yml
    - include_tasks: hostid.yml
  tags:
    - identification
    - system

- block:
    - include_tasks: directories.yml
    - include_tasks: sysctls.yml
    - include_tasks: upgrade.yml
    - include_tasks: package_manager.yml
    - include_tasks: src.yml
    - include_tasks: packages.yml
    - include_tasks: groups.yml
    - include_tasks: users.yml
    - include_tasks: sudoers.yml
    - include_tasks: hostmode.yml
    - include_tasks: fstab.yml
    - include_tasks: systemd.yml
    - include_tasks: services.yml
    - include_tasks: grub.yml
    - include_tasks: logrotate.yml
    - include_tasks: cpu_microcode.yml
    - include_tasks: zfs.yml
    - include_tasks: sshd.yml
    - include_tasks: ntpd.yml
    - include_tasks: firewall.yml
    - include_tasks: audio.yml
  tags:
    - system
