---

- include: context.yml

- block:
    - include_tasks: hosttype.yml
    - include_tasks: hostid.yml
  tags:
    - identification
    - system

- block:
    - include_tasks: directories.yml
    - include_tasks: sysctls.yml
    - include_tasks: upgrade_mode.yml
    - include_tasks: package_repositories.yml
    - include_tasks: make.yml
    - include_tasks: src.yml
    - include_tasks: ports.yml
    - include_tasks: packages.yml
    - include_tasks: groups.yml
    - include_tasks: users.yml
    - include_tasks: sudoers.yml
    - include_tasks: hostmode.yml
    - include_tasks: fstab.yml
    - include_tasks: services.yml
    - include_tasks: grub.yml
    - include_tasks: logrotate.yml
  tags:
    - system
