---
- name: packages vars
  include_vars:
    file: packages.yml

# - name: install base packages
#   package:
#     name: "{{ common_packages + specific_packages }}"
#     state: latest

- name: apt
  block:
    - name: apt based update
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: "{{ packages_cache_ttl }}"

    - name: "apt install {{ hosttype }} packages"
      apt:
        name: "{{ packages_base['common'] \
                  + (packages_base['common_' + ansible_architecture] | default([])) \
                  + (packages_base[ansible_distribution] | default([])) \
                  + (packages_base[ansible_distribution + '_' + ansible_architecture] | default([])) \
                  + (vars['packages_' + hosttype]['common'] | default([])) \
                  + (vars['packages_' + hosttype]['common_' + ansible_architecture] | default([])) \
                  + (vars['packages_' + hosttype][ansible_distribution] | default([])) \
                  + (vars['packages_' + hosttype][ansible_distribution + '_' + ansible_architecture] | default([])) \
               }}"
        state: latest
        update_cache: yes
        cache_valid_time: "{{ packages_cache_ttl }}"
        autoremove: yes

  when: ansible_pkg_mgr == 'apt'

- name: FreeBSD
  block:
    - name: update catalog
      shell: "pkg update -q"
      changed_when: false

    - name: "pkg install {{ hosttype }} packages"
      pkgng:
        name: "{{ packages_base['common'] \
                  + (packages_base['common_' + ansible_architecture] | default([])) \
                  + (packages_base[ansible_distribution] | default([])) \
                  + (packages_base[ansible_distribution + '_' + ansible_architecture] | default([])) \
                  + (vars['packages_' + hosttype]['common'] | default([])) \
                  + (vars['packages_' + hosttype]['common_' + ansible_architecture] | default([])) \
                  + (vars['packages_' + hosttype][ansible_distribution] | default([])) \
                  + (vars['packages_' + hosttype][ansible_distribution + '_' + ansible_architecture] | default([])) \
               }}"
        state: latest

  when: ansible_os_family == 'FreeBSD'
