---

- name: set pf_mode
  block:
    - set_fact:
        pf_mode: router
      when: is_router is defined and is_router
    - set_fact:
        pf_mode: "{{ hosttype }}"
      when: is_router is not defined or not is_router
  when: pf_mode is not defined

- name: inherit interfaces
  block:
    - set_fact:
        pf_lan_if: "{{ lan_if }}"
      when: lan_if is defined

    - set_fact:
        pf_ext_if: "{{ ext_if }}"
      when: ext_if is defined

- name: set interfaces on router
  block:
    - set_fact:
        pf_lan_if: "{{ ansible_default_ipv4.interface }}"
      when: pf_lan_if is not defined

    - set_fact:
        pf_ext_if: "{{ ansible_interfaces | difference([ansible_default_ipv4.interface, 'lo0', 'pflog0']) | first }}"
      when: pf_ext_if is not defined
  when: pf_mode == 'router'

- name: set interfaces on non-router
  block:
    - set_fact:
        pf_ext_if: "{{ ansible_default_ipv4.interface }}"
      when: pf_ext_if is not defined
  when: pf_mode != 'router'

- name: FreeBSD
  block:
    - name: deploy pf.conf
      template:
        src: "{{ item }}"
        dest: "{{ pf_conf_file }}"
        owner: root
        group: "{{ root_group }}"
        mode: '0440'
      vars:
        pf_conf_files:
          files:
            - "pf.{{ pf_mode }}.conf"
            - "pf.{{ hosttype }}.conf"
            - "pf.default.conf"
          paths:
            - 'templates/pf'
      loop: "{{ q('first_found', pf_conf_files) }}"
      register: t_pf_deploy_conf

    - name: check pf.blackhole file status
      stat:
        path: "{{ pf_blackhole_file }}"
      register: pf_file_status

    - name: create pf.blackhole file
      file:
        path: "{{ pf_blackhole_file }}"
        state: touch
        owner: root
        mode: 0640
      when: not pf_file_status.stat.exists

    - name: check pf.bruteforce file status
      stat:
        path: "{{ pf_bruteforce_file }}"
      register: pf_file_status

    - name: create pf.bruteforce file
      file:
        path: "{{ pf_bruteforce_file }}"
        state: touch
        owner: root
        mode: 0640
      when: not pf_file_status.stat.exists

    - name: check pf.os file status
      stat:
        path: "{{ pf_os_file }}"
      register: pf_file_status

    - name: create pf.os file
      copy:
        owner: root
        src: pf/pf.os
        dest: "{{ pf_os_file }}"
      when: not pf_file_status.stat.exists

    - name: ensure pf file permissions
      file:
        path: "{{ item.path }}"
        owner: root
        group: "{{ root_group }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: "{{ pf_os_file }}", mode: "0640" }
        - { path: "{{ pf_bruteforce_file }}", mode: "0600" }
        - { path: "{{ pf_blackhole_file }}", mode: "0600" }

    - name: enable pf services
      include: sysrc.yml entry="{{ pf_sysrc_entry }}"
      loop: "{{ pf_sysrcs }}"
      loop_control:
        loop_var: pf_sysrc_entry

    - name: set pf rules location
      include: sysrc.yml entry="{{ pf_rules_sysrc }}"
      vars:
        pf_rules_sysrc:
          name: pf_rules
          value: "{{ pf_conf_file }}"

    - name: start pf services
      service:
        name: "{{ pf_service }}"
        state: started
      loop: "{{ pf_services }}"
      loop_control:
        loop_var: pf_service

  when: ansible_distribution == 'FreeBSD'
