---

- name: install FreeBSD ports
  block:
    - name: check if installed
      stat:
        path: /usr/ports/.portsnap.INDEX
      register: stat_portsnap_index

    - name: install ports with portsnap extract
      shell: portsnap --interactive fetch extract
      when: stat_portsnap_index.stat.exists == False

    - name: update ports with portsnap fetch update
      shell: portsnap --interactive fetch update
      changed_when: no

    - name: check make.conf presence
      stat:
        path: "{{ system_make_conf }}"
      register: t_system_make_conf_stat

    - name: touch make.conf
      file:
        path: "{{ system_make_conf }}"
        owner: root
        group: "{{ root_group }}"
        mode: "0644"
        state: touch
      when: not t_system_make_conf_stat.stat.exists

    - name: deploy make.conf for ports for server
      lineinfile:
        path: "{{ system_make_conf }}"
        regexp: "^{{ item }}"
        line: "{{ item }}"
      loop: "{{ system_make_conf_server_entries }}"
      when: hosttype == 'server'

  when: ansible_system == 'FreeBSD'
